# Generated by Django 4.2 on 2024-03-29 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(default='', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryStaticSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('country_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=255, null=True)),
                ('country_official_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country_capital', models.CharField(blank=True, max_length=100, null=True)),
                ('country_un_member', models.BooleanField(blank=True, default=False, null=True)),
                ('country_region', models.CharField(blank=True, max_length=100, null=True)),
                ('country_subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('country_lat', models.FloatField(blank=True, null=True)),
                ('country_long', models.FloatField(blank=True, null=True)),
                ('country_area', models.FloatField(blank=True, null=True)),
                ('country_population', models.BigIntegerField(blank=True, null=True)),
                ('country_continent', models.CharField(blank=True, max_length=100, null=True)),
                ('country_flag', models.CharField(blank=True, max_length=255, null=True)),
                ('country_postal_code_format', models.CharField(blank=True, max_length=255, null=True)),
                ('country_postal_code_regex', models.CharField(blank=True, max_length=255, null=True)),
                ('country_google_maps_url', models.CharField(blank=True, max_length=255, null=True)),
                ('country_open_street_map_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
