# Generated by Django 4.2 on 2024-03-29 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.countryhub'),
        ),
        migrations.AddField(
            model_name='countryhub',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='countrystaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='country_cou_hash_id_c01fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='countrystaticsatellite',
            index=models.Index(fields=['hash_value'], name='country_cou_hash_va_b5e9b0_idx'),
        ),
    ]
