# Generated by Django 4.2 on 2024-03-29 09:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_initial'),
        ('country', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCountryCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.countryhub')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currencyhub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='countryhub',
            name='link_country_currency',
            field=models.ManyToManyField(related_name='link_currency_country', through='country.LinkCountryCurrency', to='currency.currencyhub'),
        ),
    ]
