# Generated by Django 4.2 on 2024-03-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0002_countryhub_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="countrystaticsatellite",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
