# Generated by Django 5.0.4 on 2024-05-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_linkcountrycurrency_countryhub_link_country_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_code_2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
