# Generated by Django 4.2 on 2024-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0003_countrystaticsatellite_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryhub",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
    ]
