# Generated by Django 4.2 on 2024-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0004_countryhub_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
    ]
