# Generated by Django 4.2 on 2024-03-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_alter_countrystaticsatellite_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_capital',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_continent',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_flag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_google_maps_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_long',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_official_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_population',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_postal_code_format',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_postal_code_regex',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_subregion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countrystaticsatellite',
            name='country_un_member',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='countryhub',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='countrystaticsatellite',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='countrystaticsatellite',
            name='country_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
