# Generated by Django 4.2 on 2024-03-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0006_countrystaticsatellite_country_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_capital",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_continent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_flag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_google_maps_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_long",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_official_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_population",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_postal_code_format",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_postal_code_regex",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_subregion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="countrystaticsatellite",
            name="country_un_member",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
