# Generated by Django 5.0.4 on 2024-05-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_countryapiuploadregistryhub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryoecdtssatellite',
            name='inflation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryoecdtssatellite',
            name='annual_fx_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
