# Generated by Django 5.0.4 on 2024-07-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_countryoecdfxannualtssatellite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryoecdfxannualtssatellite',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryoecdinflationtssatellite',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
