# Generated by Django 4.2 on 2024-03-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0007_alter_countrystaticsatellite_country_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="countrystaticsatellite",
            name="country_open_street_map_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
