# Generated by Django 5.0.4 on 2024-11-15 15:15

import baseclasses.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0005_alter_testhubvaluedate_hub'),
        ('country', '0008_alter_countryoecdfxannualtssatellite_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryoecdfxannualtssatellite',
            name='hub_entity',
        ),
        migrations.RemoveField(
            model_name='countryoecdinflationtssatellite',
            name='hub_entity',
        ),
        migrations.CreateModel(
            name='CountryHubValueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub', baseclasses.fields.HubForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_value_date', to='country.countryhub')),
                ('value_date_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.valuedatelist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='countryoecdfxannualtssatellite',
            name='hub_value_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='country.countryhubvaluedate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countryoecdinflationtssatellite',
            name='hub_value_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='country.countryhubvaluedate'),
            preserve_default=False,
        ),
    ]
