# Generated by Django 5.0.4 on 2024-11-27 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0006_testhubvaluedate_baseclasses_value_d_976969_idx_and_more'),
        ('country', '0010_countryapiuploadregistryhubvaluedate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='countryapiuploadregistryhubvaluedate',
            index=models.Index(fields=['value_date_list'], name='country_cou_value_d_828faa_idx'),
        ),
        migrations.AddIndex(
            model_name='countryapiuploadregistryhubvaluedate',
            index=models.Index(fields=['hub'], name='country_cou_hub_id_00dc95_idx'),
        ),
        migrations.AddIndex(
            model_name='countryhubvaluedate',
            index=models.Index(fields=['value_date_list'], name='country_cou_value_d_0e00d6_idx'),
        ),
        migrations.AddIndex(
            model_name='countryhubvaluedate',
            index=models.Index(fields=['hub'], name='country_cou_hub_id_409db1_idx'),
        ),
        migrations.AddIndex(
            model_name='countrystaticsatellite',
            index=models.Index(fields=['hub_entity'], name='country_cou_hub_ent_c16d6d_idx'),
        ),
    ]
