# Generated by Django 5.1.5 on 2025-03-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0011_countryapiuploadregistryhubvaluedate_country_cou_value_d_828faa_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryapiuploadregistrystaticsatellite',
            old_name='upload_message',
            new_name='import_message',
        ),
        migrations.RenameField(
            model_name='countryapiuploadregistrystaticsatellite',
            old_name='upload_status',
            new_name='import_status',
        ),
        migrations.RemoveField(
            model_name='countryapiuploadregistrystaticsatellite',
            name='url',
        ),
        migrations.AddField(
            model_name='countryapiuploadregistrystaticsatellite',
            name='import_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
