# Generated by Django 5.2.9 on 2026-05-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0012_rename_upload_message_countryapiuploadregistrystaticsatellite_import_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryapiuploadregistrystaticsatellite',
            name='celery_task_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
