# Generated by Django 4.2 on 2024-03-29 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(default='', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyStaticSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('ccy_name', models.CharField(max_length=50)),
                ('ccy_code', models.CharField(max_length=3)),
                ('ccy_symbol', models.CharField(max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyTimeSeriesSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hash_identifier', models.CharField(default='', max_length=64)),
                ('hash_value', models.CharField(default='', max_length=64)),
                ('value_date', models.DateField()),
                ('fx_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
