# Generated by Django 4.2 on 2024-03-29 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencytimeseriessatellite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencytimeseriessatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_time_series_satellites', to='currency.currencyhub'),
        ),
        migrations.AddField(
            model_name='currencystaticsatellite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencystaticsatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_static_satellites', to='currency.currencyhub'),
        ),
        migrations.AddField(
            model_name='currencyhub',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='currencystaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='currency_cu_hash_id_0fbb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='currencystaticsatellite',
            index=models.Index(fields=['hash_value'], name='currency_cu_hash_va_fa2f2e_idx'),
        ),
    ]
