# Generated by Django 4.2 on 2024-03-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencystaticsatellite',
            name='ccy_symbol',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
