# Generated by Django 4.2 on 2024-03-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0002_currencyhub_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencystaticsatellite",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="currencytimeseriessatellite",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
