# Generated by Django 4.2 on 2024-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0003_currencystaticsatellite_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencyhub",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
    ]
