# Generated by Django 5.0.4 on 2024-11-09 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_currencystaticsatellite_ccy_symbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='currencytimeseriessatellite',
            index=models.Index(fields=['hash_identifier'], name='currency_cu_hash_id_3ce7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='currencytimeseriessatellite',
            index=models.Index(fields=['hash_value'], name='currency_cu_hash_va_be6dbd_idx'),
        ),
    ]
