# Generated by Django 4.2 on 2024-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0004_currencyhub_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencystaticsatellite",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="currencytimeseriessatellite",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
    ]
