# Generated by Django 4.2 on 2024-03-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_currencystaticsatellite_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyhub',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='currencystaticsatellite',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='currencytimeseriessatellite',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
