# Generated by Django 5.0.4 on 2024-11-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_remove_currencytimeseriessatellite_hub_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytimeseriessatellite',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
