# Generated by Django 5.0.4 on 2024-11-27 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0006_testhubvaluedate_baseclasses_value_d_976969_idx_and_more'),
        ('currency', '0006_alter_currencytimeseriessatellite_fx_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='currencyhubvaluedate',
            index=models.Index(fields=['value_date_list'], name='currency_cu_value_d_5b68f5_idx'),
        ),
        migrations.AddIndex(
            model_name='currencyhubvaluedate',
            index=models.Index(fields=['hub'], name='currency_cu_hub_id_2418a3_idx'),
        ),
        migrations.AddIndex(
            model_name='currencystaticsatellite',
            index=models.Index(fields=['hub_entity'], name='currency_cu_hub_ent_0cc3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='currencytimeseriessatellite',
            index=models.Index(fields=['hub_value_date'], name='currency_cu_hub_val_612393_idx'),
        ),
    ]
