# Generated by Django 4.2 on 2024-03-29 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit_institution', '0001_initial'),
        ('country', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditinstitutionstaticsatellite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditinstitutionstaticsatellite',
            name='hub_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_institution.creditinstitutionhub'),
        ),
        migrations.AddField(
            model_name='creditinstitutionhub',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditinstitutionhub',
            name='link_credit_institution_country',
            field=models.ManyToManyField(related_name='link_country_credit_institution', through='credit_institution.LinkCreditInstitutionCountry', to='country.countryhub'),
        ),
        migrations.AddIndex(
            model_name='creditinstitutionstaticsatellite',
            index=models.Index(fields=['hash_identifier'], name='credit_inst_hash_id_3176c5_idx'),
        ),
        migrations.AddIndex(
            model_name='creditinstitutionstaticsatellite',
            index=models.Index(fields=['hash_value'], name='credit_inst_hash_va_3cd4d1_idx'),
        ),
    ]
