# Generated by Django 5.0.4 on 2024-11-10 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0004_testhubvaluedate'),
        ('credit_institution', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditInstitutionHubValueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_institution.creditinstitutionhub')),
                ('value_date_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseclasses.valuedatelist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
