# Generated by Django 5.0.4 on 2024-11-10 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_institution', '0003_creditinstitutionhubvaluedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinstitutionhubvaluedate',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_value_date', to='credit_institution.creditinstitutionhub'),
        ),
    ]
