# Generated by Django 5.0.4 on 2024-11-27 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseclasses', '0006_testhubvaluedate_baseclasses_value_d_976969_idx_and_more'),
        ('credit_institution', '0004_alter_creditinstitutionhubvaluedate_hub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditinstitutionhubvaluedate',
            index=models.Index(fields=['value_date_list'], name='credit_inst_value_d_8ae304_idx'),
        ),
        migrations.AddIndex(
            model_name='creditinstitutionhubvaluedate',
            index=models.Index(fields=['hub'], name='credit_inst_hub_id_39921d_idx'),
        ),
        migrations.AddIndex(
            model_name='creditinstitutionstaticsatellite',
            index=models.Index(fields=['hub_entity'], name='credit_inst_hub_ent_c4219b_idx'),
        ),
    ]
