# Generated by Django 4.2 on 2024-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_institution", "0004_creditinstitutionstaticsatellite_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditinstitutionhub",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="linkcreditinstitutioncountry",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
    ]
