# Generated by Django 4.2 on 2024-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_institution", "0005_creditinstitutionhub_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditinstitutionstaticsatellite",
            name="comment",
            field=models.CharField(default="", max_length=255),
        ),
    ]
