# Generated by Django 5.0.4 on 2025-01-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_institution', '0005_creditinstitutionhubvaluedate_credit_inst_value_d_8ae304_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinstitutionstaticsatellite',
            name='account_upload_method',
            field=models.CharField(choices=[('none', 'None'), ('dkb', 'Dkb'), ('onvis', 'Onvista'), ('trrep', 'Trade Republic'), ('qonex', 'Qonto Excel')], default='none', max_length=5),
        ),
    ]
