# Generated by Django 5.1.5 on 2025-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_institution', '0006_alter_creditinstitutionstaticsatellite_account_upload_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinstitutionstaticsatellite',
            name='account_upload_method',
            field=models.CharField(choices=[('none', 'None'), ('dkb', 'Dkb'), ('onvis', 'Onvista'), ('trrep', 'Trade Republic'), ('qonex', 'Qonto Excel'), ('qoapi', 'Qonto Api')], default='none', max_length=5),
        ),
    ]
