# Generated by Django 4.2 on 2024-03-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_institution', '0006_alter_creditinstitutionstaticsatellite_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinstitutionhub',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='creditinstitutionstaticsatellite',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='linkcreditinstitutioncountry',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
