from django.urls import path
from mt_economic_common.country import views

urlpatterns = [
    path(
        "overview",
        views.CountryOverview.as_view(),
        name="country",
    ),
    path(
        "create",
        views.CountryCreateView.as_view(),
        name="country_create",
    ),
    path(
        "details/<int:pk>",
        views.CountryDetailsView.as_view(),
        name="country_details",
    ),
    path(
        "update/<int:pk>",
        views.CountryUpdateView.as_view(),
        name="country_update",
    ),
    path(
        "api_registry",
        views.CountryApiRegistryListView.as_view(),
        name="country_api_registry_list",
    ),
    path(
        "upload_countries_rest_countries",
        views.upload_countries_rest_countries,
        name="upload_countries_rest_countries",
    ),
    path(
        "map/<int:pk>",
        views.CountryMapView.as_view(),
        name="country_map",
    ),
    path(
        "upload_oecd_country_data",
        views.upload_oecd_country_data,
        name="upload_oecd_country_data",
    ),
    path(
        "country_oecd_data/<int:pk>",
        views.CountryOecdDataView.as_view(),
        name="country_oecd_data",
    ),
]
